### ISSUE TITLE
Project Feedback - Ziyuan Zhu

### ISSUE THREAD

**Issue by ziyuanzhu1** [Tom-Fang00/Tom-Personal-Website#3]
Technical Issues:
- On the navigation bar, a suggestion I would give is to give color to the menu when users hover over it. A hover effect can give them a clear signal to see what's clickable. 
- Make sure to add a Favicon image to your page so it doesn't just have the earth icon.

Content Suggestions:
- I would add Yelp Reviews to the site as a tab just to add social proof to your website. Your potential clients will know that you're a trusted brand. Customer feedback will give you insights into how you could improve your product and the overall buying experience.
- For aesthetic purposes, I would move your logo to the left side or the top-middle side instead of being directly in between the navigation bar. I find it a bit odd looking since the font size and font family are different from each other.

**Comment by Tom-Fang00** [comment]
Thanks for the suggestions, I have created a favicon and added hovering effects to the navigation bar
