### ISSUE TITLE
Project Peer Review Comments

### ISSUE THREAD

**Issue by dmcnamara1** [Tom-Fang00/Tom-Personal-Website#4]
Technical Issue #1: Not all your images were defined using both “alt” and “title”, as the requirements stated.

Technical Issue #2: There is no favicon added to be displayed on your tab for site visitors. Not only was this a requirement in the assignment, but it also adds a lot of life to the website subliminally and highly recommend you incorporate it.

Content Recommendation #1: I see what you’re trying to do with the all over page collage of pictures, but I think it would be good to think about this. If you want to stick with this, I would recommend editing it so the layout and picture sizes don’t change as you increase or decrease the window size; fixed instead of adaptive.

Content Recommendation #2: I think you should definitely add a lot of CSS to your footer. The all white at bottom right with no type of style looks not as professional as it could. You can also explore adding more content/links into footer, but either way I think styling it would be very beneficial.

**Comment by Tom-Fang00** [comment]
Thanks for the suggestions, Added the favicon and alt/titles for the images.
